### PR TITLE
PSSM not loaded

### PR DESCRIPTION
**Pull request by jyaacoub**
Hi, I am building off of your model and was rewriting some code in a separate private repo and encountered this issue.

At the critical point where the PSSM feature is to be loaded and concatenated with the rest of the residue node features there is a mistake that causes it to never be read in and all we get is zeros.

To confirm this I set that portion to np.zeros() and found that when I run `python test.py 0 0` the results don't change. Looking into this a bit further I visualized the first layer weights (from the model checkpoints you provided) and we can clearly see that the model doesn't know what to do with the first 21 columns of the node feature matrix which represents the PSSM matrix:

image
image

I don't think this is a big issue since it doesn't really change the paper's conclusion much, but it should be noted for future researchers. I was also curious how you tested the significance of the PSSM matrix in section 3.6 of your paper, perhaps I am missing something here, since given this issue there should be no difference.

In my own work, I am working with the PDBbind dataset and found no difference after properly setting up the MSAs for the PSSM matrix.

### CODE REVIEW

**Comment by jyaacoub** [comment]
the mistake is in `data_process.py` line 149 (`PSSM_calculation()`):

```python
def PSSM_calculation(aln_file, pro_seq):
    pfm_mat = np.zeros((len(pro_res_table), len(pro_seq)))
    with open(aln_file, 'r') as f:
        line_count = len(f.readlines()) # CANT GET THE LINE COUNT LIKE THIS BC THE FILE OBJECT BECOMES EMPTY AFTER THE FIRST READ
        for line in f.readlines(): # ERROR: BIG ISSUE HERE - f.readlines() is empty. FOR LOOP NEVER EXECUTES
            if len(line) != len(pro_seq):
                print('error', len(line), len(pro_seq))
                continue
            count = 0
```

**Comment by daydayupzzl** [comment]
> the mistake is in `data_process.py` line 149 (`PSSM_calculation()`)

What you found is crucial! May I ask if there has been any change in model accuracy after correcting this error and retraining? Thank you. Looking forward to your reply

**Comment by jyaacoub** [comment]
~~I trained it for 50 epochs to test, but no I didn't see a substantial difference. See my latest commits for more details (https://github.com/595693085/DGraphDTA/pull/15/commits/a48bc453c9b900687168c36741921d5e7a3b86cd).~~

**Comment by jyaacoub** [comment]
Disregard the last comment, I forgot to remove np.zeros that I had placed initially for testing.

**Comment by jyaacoub** [comment]
I fixed this and retrained for 50 epochs. It seems like there is a boost to performance with CI going from 0.78 -> 0.80 and MSE from 0.55 to 0.52, but it is only slight. 

You can try it yourself, but note that it does take a while to prepare (5-20 mins depending on your machine) since we are actually reading the values from the alignment files now.

**Comment by daydayupzzl** [comment]
Thank you for your response and for sharing your experiments. I am looking forward to further communication and collaboration in the field of drug discovery and manufacturing. Feel free to contact me via email at [daydayupzzl@163.com]or [daydayupzzl@outlook.com]

**Comment by daydayupzzl** [comment]
> I fixed this and retrained for 50 epochs. It seems like there is a boost to performance with CI going from 0.78 -> 0.80 and MSE from 0.55 to 0.52, but it is only slight.
> 
> You can try it yourself, but note that it does take a while to prepare (5-20 mins depending on your machine) since we are actually reading the values from the alignment files now.

Thank you for your response and for sharing your experiments. From this issue, I can see that you pay attention to details and also have strong coding skills. I am interested in further communication and collaboration in the field of drug discovery and manufacturing. Feel free to contact me via email at [[daydayupzzl@163.com](mailto:daydayupzzl@163.com)]or [[daydayupzzl@outlook.com](mailto:daydayupzzl@outlook.com)]. Keep up the good work!

**Pull request closed without merging**
